

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class MessageEnvelope : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the MessageEnvelope entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MessageEnvelope()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MessageEnvelope(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MessageEnvelope> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.MessageEnvelope.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MessageEnvelope_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MessageEnvelope_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.MessageEnvelope.DetailsClass.GetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.MessageEnvelope.DetailsClass.SetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int RowVersion
        {
            get
            {
                return global::LightSwitchApplication.MessageEnvelope.DetailsClass.GetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.MessageEnvelope.DetailsClass.SetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Message
        {
            get
            {
                return global::LightSwitchApplication.MessageEnvelope.DetailsClass.GetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Message);
            }
            set
            {
                global::LightSwitchApplication.MessageEnvelope.DetailsClass.SetValue(this, global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Message, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.MessageEnvelope,
                global::LightSwitchApplication.MessageEnvelope.DetailsClass,
                global::LightSwitchApplication.MessageEnvelope.DetailsClass.IImplementation,
                global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>.Entry
                __MessageEnvelopeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>.Entry(
                    global::LightSwitchApplication.MessageEnvelope.DetailsClass.__MessageEnvelope_CreateNew,
                    global::LightSwitchApplication.MessageEnvelope.DetailsClass.__MessageEnvelope_Created,
                    global::LightSwitchApplication.MessageEnvelope.DetailsClass.__MessageEnvelope_AllowSaveWithErrors);
            private static global::LightSwitchApplication.MessageEnvelope __MessageEnvelope_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MessageEnvelope> es)
            {
                return new global::LightSwitchApplication.MessageEnvelope(es);
            }
            private static void __MessageEnvelope_Created(global::LightSwitchApplication.MessageEnvelope e)
            {
                e.MessageEnvelope_Created();
            }
            private static bool __MessageEnvelope_AllowSaveWithErrors(global::LightSwitchApplication.MessageEnvelope e)
            {
                bool result = false;
                e.MessageEnvelope_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]> Message
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties.Message) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int RowVersion { get; set; }
                new byte[] Message { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MessageEnvelope.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Data> c, global::LightSwitchApplication.MessageEnvelope.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.MessageEnvelope e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.MessageEnvelope e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.MessageEnvelope e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MessageEnvelope.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Data> c, global::LightSwitchApplication.MessageEnvelope.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.MessageEnvelope e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.MessageEnvelope e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static int _RowVersion_GetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d, int v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.MessageEnvelope e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]>.Entry
                    Message = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]>.Entry(
                        "Message",
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_Stub,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_ComputeIsReadOnly,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_Validate,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_GetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_SetImplementationValue,
                        global::LightSwitchApplication.MessageEnvelope.DetailsClass.PropertySetProperties._Message_OnValueChanged);
                private static void _Message_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MessageEnvelope.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.MessageEnvelope.DetailsClass d, object sf)
                {
                    c(d, ref d._Message, sf);
                }
                private static bool _Message_ComputeIsReadOnly(global::LightSwitchApplication.MessageEnvelope e)
                {
                    bool result = false;
                    e.Message_IsReadOnly(ref result);
                    return result;
                }
                private static void _Message_Validate(global::LightSwitchApplication.MessageEnvelope e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Message_Validate(r);
                }
                private static byte[] _Message_GetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d)
                {
                    return d.ImplementationEntity.Message;
                }
                private static void _Message_SetImplementationValue(global::LightSwitchApplication.MessageEnvelope.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Message = v;
                }
                private static void _Message_OnValueChanged(global::LightSwitchApplication.MessageEnvelope e)
                {
                    e.Message_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, int>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MessageEnvelope, global::LightSwitchApplication.MessageEnvelope.DetailsClass, byte[]>.Data _Message;
            
        }
    
        #endregion
    }
    
    #endregion
}
