//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Ability to delete companies.  Deleting companies could destroy data integrity.
        /// </summary>
        public const string DeleteCompanies = "LightSwitchApplication:DeleteCompanies";
        /// <summary>
        /// Ability to add/edit companies
        /// </summary>
        public const string EditCompanies = "LightSwitchApplication:EditCompanies";
        /// <summary>
        /// Ability to edit the next job number to create for each company
        /// </summary>
        public const string EditNextJobNo = "LightSwitchApplication:EditNextJobNo";
        /// <summary>
        /// OverridePartNumber
        /// </summary>
        public const string OverridePartNumber = "LightSwitchApplication:OverridePartNumber";
        /// <summary>
        /// Used in elevated permissions for code to override user permissions.
        /// </summary>
        public const string OverrideBySystem = "LightSwitchApplication:OverrideBySystem";
        /// <summary>
        /// OverrideNextPONo
        /// </summary>
        public const string OverrideNextPONo = "LightSwitchApplication:OverrideNextPONo";
        /// <summary>
        /// Allows PO Status on a closed order to be reset to the first status.
        /// </summary>
        public const string OverrideClosedStatus = "LightSwitchApplication:OverrideClosedStatus";
        /// <summary>
        /// EditProducts
        /// </summary>
        public const string EditProducts = "LightSwitchApplication:EditProducts";
        /// <summary>
        /// EditJobs
        /// </summary>
        public const string EditJobs = "LightSwitchApplication:EditJobs";
        /// <summary>
        /// EditPOs
        /// </summary>
        public const string EditPOs = "LightSwitchApplication:EditPOs";
        /// <summary>
        /// EditMessages
        /// </summary>
        public const string EditMessages = "LightSwitchApplication:EditMessages";
        /// <summary>
        /// EditSettings
        /// </summary>
        public const string EditSettings = "LightSwitchApplication:EditSettings";
        /// <summary>
        /// HideLogoGroup
        /// </summary>
        public const string HideLogoGroup = "LightSwitchApplication:HideLogoGroup";
        /// <summary>
        /// EditReleases
        /// </summary>
        public const string EditReleases = "LightSwitchApplication:EditReleases";
        /// <summary>
        /// ProcessDuplicatesFirst
        /// </summary>
        public const string ProcessDuplicatesFirst = "LightSwitchApplication:ProcessDuplicatesFirst";
        /// <summary>
        /// DeleteInvoices
        /// </summary>
        public const string DeleteInvoices = "LightSwitchApplication:DeleteInvoices";
        /// <summary>
        /// EditInvoices
        /// </summary>
        public const string EditInvoices = "LightSwitchApplication:EditInvoices";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
