

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class PurchaseOrderLine : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PurchaseOrderLine entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PurchaseOrderLine()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PurchaseOrderLine(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PurchaseOrderLine> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderLine_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderLine_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// If you select an item from Avail JobMasterBOMItem, The Product changes to it.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> JobMasterBOMItemId
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.JobMasterBOMItemId);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.JobMasterBOMItemId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBOMItemId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBOMItemId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBOMItemId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal OrderQty
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.OrderQty);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.OrderQty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderQty_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string VendorPartNo
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.VendorPartNo);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.VendorPartNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VendorPartNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VendorPartNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VendorPartNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LineNotes
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.LineNotes);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.LineNotes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineNotes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineNotes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineNotes_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsComplete
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.IsComplete);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.IsComplete, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsComplete_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsComplete_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsComplete_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Price
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Price);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Price, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ReceivedQty
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.ReceivedQty);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReceivedQty_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReceivedQty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> ExtPrice
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.ExtPrice);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExtPrice_Compute(ref global::System.Nullable<decimal> result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExtPrice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PartsPath
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PartsPath);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartsPath_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartsPath_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string VendorName
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.VendorName);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VendorName_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VendorName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.PurchaseOrder PurchaseOrder
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrder_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrder_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrder_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Product Product
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Receipt> Receipts
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Receipts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Receipt> ReceiptsQuery
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.GetQuery(this, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Receipts);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PurchaseOrderLine,
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass,
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.IImplementation,
                global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>.Entry
                __PurchaseOrderLineEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>.Entry(
                    global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.__PurchaseOrderLine_CreateNew,
                    global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.__PurchaseOrderLine_Created,
                    global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.__PurchaseOrderLine_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PurchaseOrderLine __PurchaseOrderLine_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PurchaseOrderLine> es)
            {
                return new global::LightSwitchApplication.PurchaseOrderLine(es);
            }
            private static void __PurchaseOrderLine_Created(global::LightSwitchApplication.PurchaseOrderLine e)
            {
                e.PurchaseOrderLine_Created();
            }
            private static bool __PurchaseOrderLine_AllowSaveWithErrors(global::LightSwitchApplication.PurchaseOrderLine e)
            {
                bool result = false;
                e.PurchaseOrderLine_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>> JobMasterBOMItemId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.JobMasterBOMItemId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal> OrderQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.OrderQty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string> VendorPartNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.VendorPartNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string> LineNotes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.LineNotes) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool> IsComplete
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.IsComplete) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal> Price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Price) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal> ReceivedQty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.ReceivedQty) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>> ExtPrice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.ExtPrice) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string> PartsPath
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PartsPath) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string> VendorName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.VendorName) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder> PurchaseOrder
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product> Product
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt> Receipts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Receipts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.Nullable<int> JobMasterBOMItemId { get; set; }
                new decimal OrderQty { get; set; }
                new string VendorPartNo { get; set; }
                new string LineNotes { get; set; }
                new bool IsComplete { get; set; }
                new decimal Price { get; set; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation PurchaseOrder { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Product { get; set; }
                new global::System.Collections.IEnumerable Receipts { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>>.Entry
                    JobMasterBOMItemId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>>.Entry(
                        "JobMasterBOMItemId",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._JobMasterBOMItemId_OnValueChanged);
                private static void _JobMasterBOMItemId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._JobMasterBOMItemId, sf);
                }
                private static bool _JobMasterBOMItemId_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.JobMasterBOMItemId_IsReadOnly(ref result);
                    return result;
                }
                private static void _JobMasterBOMItemId_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JobMasterBOMItemId_Validate(r);
                }
                private static global::System.Nullable<int> _JobMasterBOMItemId_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.JobMasterBOMItemId;
                }
                private static void _JobMasterBOMItemId_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.JobMasterBOMItemId = v;
                }
                private static void _JobMasterBOMItemId_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.JobMasterBOMItemId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry
                    OrderQty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry(
                        "OrderQty",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._OrderQty_OnValueChanged);
                private static void _OrderQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderQty, sf);
                }
                private static bool _OrderQty_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.OrderQty_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderQty_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderQty_Validate(r);
                }
                private static decimal _OrderQty_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderQty;
                }
                private static void _OrderQty_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.OrderQty = v;
                }
                private static void _OrderQty_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.OrderQty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry
                    VendorPartNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry(
                        "VendorPartNo",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorPartNo_OnValueChanged);
                private static void _VendorPartNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._VendorPartNo, sf);
                }
                private static bool _VendorPartNo_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.VendorPartNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _VendorPartNo_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VendorPartNo_Validate(r);
                }
                private static string _VendorPartNo_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.VendorPartNo;
                }
                private static void _VendorPartNo_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, string v)
                {
                    d.ImplementationEntity.VendorPartNo = v;
                }
                private static void _VendorPartNo_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.VendorPartNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry
                    LineNotes = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry(
                        "LineNotes",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._LineNotes_OnValueChanged);
                private static void _LineNotes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._LineNotes, sf);
                }
                private static bool _LineNotes_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.LineNotes_IsReadOnly(ref result);
                    return result;
                }
                private static void _LineNotes_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LineNotes_Validate(r);
                }
                private static string _LineNotes_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.LineNotes;
                }
                private static void _LineNotes_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LineNotes = v;
                }
                private static void _LineNotes_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.LineNotes_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool>.Entry
                    IsComplete = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool>.Entry(
                        "IsComplete",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._IsComplete_OnValueChanged);
                private static void _IsComplete_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._IsComplete, sf);
                }
                private static bool _IsComplete_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.IsComplete_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsComplete_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsComplete_Validate(r);
                }
                private static bool _IsComplete_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.IsComplete;
                }
                private static void _IsComplete_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsComplete = v;
                }
                private static void _IsComplete_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.IsComplete_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry
                    Price = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry(
                        "Price",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Price_OnValueChanged);
                private static void _Price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._Price, sf);
                }
                private static bool _Price_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.Price_IsReadOnly(ref result);
                    return result;
                }
                private static void _Price_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Price_Validate(r);
                }
                private static decimal _Price_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.Price;
                }
                private static void _Price_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Price = v;
                }
                private static void _Price_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.Price_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry
                    ReceivedQty = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Entry(
                        "ReceivedQty",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ReceivedQty_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ReceivedQty_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ReceivedQty_ComputeValue);
                private static void _ReceivedQty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._ReceivedQty, sf);
                }
                private static void _ReceivedQty_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ReceivedQty_Validate(r);
                }
                private static decimal _ReceivedQty_ComputeValue(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    decimal value = default(decimal);
                    e.ReceivedQty_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>>.Entry
                    ExtPrice = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "ExtPrice",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ExtPrice_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ExtPrice_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._ExtPrice_ComputeValue);
                private static void _ExtPrice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._ExtPrice, sf);
                }
                private static void _ExtPrice_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ExtPrice_Validate(r);
                }
                private static global::System.Nullable<decimal> _ExtPrice_ComputeValue(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    global::System.Nullable<decimal> value = default(global::System.Nullable<decimal>);
                    e.ExtPrice_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry
                    PartsPath = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry(
                        "PartsPath",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PartsPath_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PartsPath_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PartsPath_ComputeValue);
                private static void _PartsPath_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._PartsPath, sf);
                }
                private static void _PartsPath_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PartsPath_Validate(r);
                }
                private static string _PartsPath_ComputeValue(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    string value = default(string);
                    e.PartsPath_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry
                    VendorName = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Entry(
                        "VendorName",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorName_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorName_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._VendorName_ComputeValue);
                private static void _VendorName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._VendorName, sf);
                }
                private static void _VendorName_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VendorName_Validate(r);
                }
                private static string _VendorName_ComputeValue(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    string value = default(string);
                    e.VendorName_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Entry
                    PurchaseOrder = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Entry(
                        "PurchaseOrder",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_GetCoreImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_Refresh,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._PurchaseOrder_OnValueChanged);
                private static void _PurchaseOrder_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchaseOrder, sf);
                }
                private static bool _PurchaseOrder_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.PurchaseOrder_IsReadOnly(ref result);
                    return result;
                }
                private static void _PurchaseOrder_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PurchaseOrder_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _PurchaseOrder_GetCoreImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchaseOrder;
                }
                private static global::LightSwitchApplication.PurchaseOrder _PurchaseOrder_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.PurchaseOrder, global::LightSwitchApplication.PurchaseOrder.DetailsClass>(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder, ref d._PurchaseOrder);
                }
                private static void _PurchaseOrder_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, global::LightSwitchApplication.PurchaseOrder v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder, ref d._PurchaseOrder, (i, ev) => i.PurchaseOrder = ev, v);
                }
                private static void _PurchaseOrder_Refresh(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.PurchaseOrder, ref d._PurchaseOrder);
                }
                private static void _PurchaseOrder_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.PurchaseOrder_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Product = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Product",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_Validate,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_GetCoreImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_Refresh,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Product_OnValueChanged);
                private static void _Product_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._Product, sf);
                }
                private static bool _Product_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    bool result = false;
                    e.Product_IsReadOnly(ref result);
                    return result;
                }
                private static void _Product_Validate(global::LightSwitchApplication.PurchaseOrderLine e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Product_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Product_GetCoreImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.Product;
                }
                private static global::LightSwitchApplication.Product _Product_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, global::LightSwitchApplication.Product v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product, ref d._Product, (i, ev) => i.Product = ev, v);
                }
                private static void _Product_Refresh(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_OnValueChanged(global::LightSwitchApplication.PurchaseOrderLine e)
                {
                    e.Product_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt>.Entry
                    Receipts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt>.Entry(
                        "Receipts",
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Receipts_Stub,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Receipts_GetReferencedEntities,
                        global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties._Receipts_GetEntityCollection);
                private static void _Receipts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt>.Data> c, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d, object sf)
                {
                    c(d, ref d._Receipts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Receipt> _Receipts_GetReferencedEntities(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Receipt, global::LightSwitchApplication.Receipt.DetailsClass>(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass.PropertySetProperties.Receipts, ref d._Receipts);
                }
                private static global::System.Collections.IEnumerable _Receipts_GetEntityCollection(global::LightSwitchApplication.PurchaseOrderLine.DetailsClass d)
                {
                    return d.ImplementationEntity.Receipts;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<int>>.Data _JobMasterBOMItemId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data _OrderQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data _VendorPartNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data _LineNotes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, bool>.Data _IsComplete;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data _Price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, decimal>.Data _ReceivedQty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::System.Nullable<decimal>>.Data _ExtPrice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data _PartsPath;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, string>.Data _VendorName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Data _PurchaseOrder;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Product>.Data _Product;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderLine, global::LightSwitchApplication.PurchaseOrderLine.DetailsClass, global::LightSwitchApplication.Receipt>.Data _Receipts;
            
        }
    
        #endregion
    }
    
    #endregion
}
