

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Unit : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Unit entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Unit()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Unit(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Unit> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Unit.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Unit_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Unit_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Unit.DetailsClass.SetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UnitOfMeasure
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitOfMeasure);
            }
            set
            {
                global::LightSwitchApplication.Unit.DetailsClass.SetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitOfMeasure, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitOfMeasure_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitOfMeasure_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitOfMeasure_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UnitCode
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitCode);
            }
            set
            {
                global::LightSwitchApplication.Unit.DetailsClass.SetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Unit.DetailsClass.SetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Product> Products
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetValue(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Products);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Product> ProductsQuery
        {
            get
            {
                return global::LightSwitchApplication.Unit.DetailsClass.GetQuery(this, global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Products);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Unit,
                global::LightSwitchApplication.Unit.DetailsClass,
                global::LightSwitchApplication.Unit.DetailsClass.IImplementation,
                global::LightSwitchApplication.Unit.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>.Entry
                __UnitEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>.Entry(
                    global::LightSwitchApplication.Unit.DetailsClass.__Unit_CreateNew,
                    global::LightSwitchApplication.Unit.DetailsClass.__Unit_Created,
                    global::LightSwitchApplication.Unit.DetailsClass.__Unit_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Unit __Unit_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Unit> es)
            {
                return new global::LightSwitchApplication.Unit(es);
            }
            private static void __Unit_Created(global::LightSwitchApplication.Unit e)
            {
                e.Unit_Created();
            }
            private static bool __Unit_AllowSaveWithErrors(global::LightSwitchApplication.Unit e)
            {
                bool result = false;
                e.Unit_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Unit.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string> UnitOfMeasure
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitOfMeasure) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string> UnitCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.UnitCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product> Products
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Products) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string UnitOfMeasure { get; set; }
                new string UnitCode { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Products { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Unit.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int>.Data> c, global::LightSwitchApplication.Unit.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Unit e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Unit e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Unit e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Entry
                    UnitOfMeasure = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Entry(
                        "UnitOfMeasure",
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_Stub,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_ComputeIsReadOnly,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_Validate,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_GetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_SetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitOfMeasure_OnValueChanged);
                private static void _UnitOfMeasure_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Unit.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Data> c, global::LightSwitchApplication.Unit.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitOfMeasure, sf);
                }
                private static bool _UnitOfMeasure_ComputeIsReadOnly(global::LightSwitchApplication.Unit e)
                {
                    bool result = false;
                    e.UnitOfMeasure_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitOfMeasure_Validate(global::LightSwitchApplication.Unit e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitOfMeasure_Validate(r);
                }
                private static string _UnitOfMeasure_GetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitOfMeasure;
                }
                private static void _UnitOfMeasure_SetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UnitOfMeasure = v;
                }
                private static void _UnitOfMeasure_OnValueChanged(global::LightSwitchApplication.Unit e)
                {
                    e.UnitOfMeasure_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Entry
                    UnitCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Entry(
                        "UnitCode",
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_Stub,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_Validate,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_GetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_SetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._UnitCode_OnValueChanged);
                private static void _UnitCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Unit.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Data> c, global::LightSwitchApplication.Unit.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitCode, sf);
                }
                private static bool _UnitCode_ComputeIsReadOnly(global::LightSwitchApplication.Unit e)
                {
                    bool result = false;
                    e.UnitCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitCode_Validate(global::LightSwitchApplication.Unit e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitCode_Validate(r);
                }
                private static string _UnitCode_GetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitCode;
                }
                private static void _UnitCode_SetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UnitCode = v;
                }
                private static void _UnitCode_OnValueChanged(global::LightSwitchApplication.Unit e)
                {
                    e.UnitCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Unit.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Unit.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Unit e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Unit e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Unit.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Unit e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products",
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Products_Stub,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Products_GetReferencedEntities,
                        global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties._Products_GetEntityCollection);
                private static void _Products_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Unit.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.Unit.DetailsClass d, object sf)
                {
                    c(d, ref d._Products, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Product> _Products_GetReferencedEntities(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.Unit.DetailsClass.PropertySetProperties.Products, ref d._Products);
                }
                private static global::System.Collections.IEnumerable _Products_GetEntityCollection(global::LightSwitchApplication.Unit.DetailsClass d)
                {
                    return d.ImplementationEntity.Products;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Data _UnitOfMeasure;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, string>.Data _UnitCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Unit, global::LightSwitchApplication.Unit.DetailsClass, global::LightSwitchApplication.Product>.Data _Products;
            
        }
    
        #endregion
    }
    
    #endregion
}
