

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Explosion : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Explosion entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Explosion()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Explosion(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Explosion> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Explosion.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Explosion_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Explosion_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Explosion.DetailsClass.GetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Explosion.DetailsClass.SetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Explosion.DetailsClass.GetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Explosion.DetailsClass.SetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int JobMasterBomId
        {
            get
            {
                return global::LightSwitchApplication.Explosion.DetailsClass.GetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.JobMasterBomId);
            }
            set
            {
                global::LightSwitchApplication.Explosion.DetailsClass.SetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.JobMasterBomId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBomId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBomId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobMasterBomId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Action
        {
            get
            {
                return global::LightSwitchApplication.Explosion.DetailsClass.GetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Action);
            }
            set
            {
                global::LightSwitchApplication.Explosion.DetailsClass.SetValue(this, global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Action, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Action_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Action_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Action_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Explosion,
                global::LightSwitchApplication.Explosion.DetailsClass,
                global::LightSwitchApplication.Explosion.DetailsClass.IImplementation,
                global::LightSwitchApplication.Explosion.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>.Entry
                __ExplosionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>.Entry(
                    global::LightSwitchApplication.Explosion.DetailsClass.__Explosion_CreateNew,
                    global::LightSwitchApplication.Explosion.DetailsClass.__Explosion_Created,
                    global::LightSwitchApplication.Explosion.DetailsClass.__Explosion_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Explosion __Explosion_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Explosion> es)
            {
                return new global::LightSwitchApplication.Explosion(es);
            }
            private static void __Explosion_Created(global::LightSwitchApplication.Explosion e)
            {
                e.Explosion_Created();
            }
            private static bool __Explosion_AllowSaveWithErrors(global::LightSwitchApplication.Explosion e)
            {
                bool result = false;
                e.Explosion_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Explosion.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int> JobMasterBomId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.JobMasterBomId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int> Action
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties.Action) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new int JobMasterBomId { get; set; }
                new int Action { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Explosion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data> c, global::LightSwitchApplication.Explosion.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Explosion e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Explosion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Explosion e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Explosion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Explosion.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Explosion e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Explosion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Explosion e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry
                    JobMasterBomId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry(
                        "JobMasterBomId",
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_Stub,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_Validate,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_GetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_SetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._JobMasterBomId_OnValueChanged);
                private static void _JobMasterBomId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Explosion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data> c, global::LightSwitchApplication.Explosion.DetailsClass d, object sf)
                {
                    c(d, ref d._JobMasterBomId, sf);
                }
                private static bool _JobMasterBomId_ComputeIsReadOnly(global::LightSwitchApplication.Explosion e)
                {
                    bool result = false;
                    e.JobMasterBomId_IsReadOnly(ref result);
                    return result;
                }
                private static void _JobMasterBomId_Validate(global::LightSwitchApplication.Explosion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.JobMasterBomId_Validate(r);
                }
                private static int _JobMasterBomId_GetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d)
                {
                    return d.ImplementationEntity.JobMasterBomId;
                }
                private static void _JobMasterBomId_SetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d, int v)
                {
                    d.ImplementationEntity.JobMasterBomId = v;
                }
                private static void _JobMasterBomId_OnValueChanged(global::LightSwitchApplication.Explosion e)
                {
                    e.JobMasterBomId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry
                    Action = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Entry(
                        "Action",
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_Stub,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_ComputeIsReadOnly,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_Validate,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_GetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_SetImplementationValue,
                        global::LightSwitchApplication.Explosion.DetailsClass.PropertySetProperties._Action_OnValueChanged);
                private static void _Action_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Explosion.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data> c, global::LightSwitchApplication.Explosion.DetailsClass d, object sf)
                {
                    c(d, ref d._Action, sf);
                }
                private static bool _Action_ComputeIsReadOnly(global::LightSwitchApplication.Explosion e)
                {
                    bool result = false;
                    e.Action_IsReadOnly(ref result);
                    return result;
                }
                private static void _Action_Validate(global::LightSwitchApplication.Explosion e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Action_Validate(r);
                }
                private static int _Action_GetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d)
                {
                    return d.ImplementationEntity.Action;
                }
                private static void _Action_SetImplementationValue(global::LightSwitchApplication.Explosion.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Action = v;
                }
                private static void _Action_OnValueChanged(global::LightSwitchApplication.Explosion e)
                {
                    e.Action_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data _JobMasterBomId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Explosion, global::LightSwitchApplication.Explosion.DetailsClass, int>.Data _Action;
            
        }
    
        #endregion
    }
    
    #endregion
}
