

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Invoice : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Invoice entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Invoice()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Invoice(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Invoice> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Invoice.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoice_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoice_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Number
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Number);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Number, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Number_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Number_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Number_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Amount
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Amount);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Amount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Amount_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateDue
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateDue);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateDue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateDue_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateInvoiced
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateInvoiced);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateInvoiced, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateInvoiced_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateInvoiced_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateInvoiced_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Notes
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Notes);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Notes, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Notes_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SearchTerms
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.SearchTerms);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.SearchTerms, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchTerms_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchTerms_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchTerms_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.InvoiceStatus InvoiceStatus
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Job Job
        {
            get
            {
                return global::LightSwitchApplication.Invoice.DetailsClass.GetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job);
            }
            set
            {
                global::LightSwitchApplication.Invoice.DetailsClass.SetValue(this, global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Job_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Invoice,
                global::LightSwitchApplication.Invoice.DetailsClass,
                global::LightSwitchApplication.Invoice.DetailsClass.IImplementation,
                global::LightSwitchApplication.Invoice.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>.Entry
                __InvoiceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>.Entry(
                    global::LightSwitchApplication.Invoice.DetailsClass.__Invoice_CreateNew,
                    global::LightSwitchApplication.Invoice.DetailsClass.__Invoice_Created,
                    global::LightSwitchApplication.Invoice.DetailsClass.__Invoice_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Invoice __Invoice_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Invoice> es)
            {
                return new global::LightSwitchApplication.Invoice(es);
            }
            private static void __Invoice_Created(global::LightSwitchApplication.Invoice e)
            {
                e.Invoice_Created();
            }
            private static bool __Invoice_AllowSaveWithErrors(global::LightSwitchApplication.Invoice e)
            {
                bool result = false;
                e.Invoice_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Invoice.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string> Number
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Number) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal> Amount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Amount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>> DateDue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateDue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>> DateInvoiced
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.DateInvoiced) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string> Notes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Notes) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string> SearchTerms
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.SearchTerms) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus> InvoiceStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job> Job
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Number { get; set; }
                new decimal Amount { get; set; }
                new global::System.Nullable<global::System.DateTime> DateDue { get; set; }
                new global::System.Nullable<global::System.DateTime> DateInvoiced { get; set; }
                new string Notes { get; set; }
                new string SearchTerms { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation InvoiceStatus { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Job { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry
                    Number = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry(
                        "Number",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Number_OnValueChanged);
                private static void _Number_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._Number, sf);
                }
                private static bool _Number_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.Number_IsReadOnly(ref result);
                    return result;
                }
                private static void _Number_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Number_Validate(r);
                }
                private static string _Number_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.Number;
                }
                private static void _Number_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Number = v;
                }
                private static void _Number_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.Number_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal>.Entry
                    Amount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal>.Entry(
                        "Amount",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Amount_OnValueChanged);
                private static void _Amount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._Amount, sf);
                }
                private static bool _Amount_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.Amount_IsReadOnly(ref result);
                    return result;
                }
                private static void _Amount_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Amount_Validate(r);
                }
                private static decimal _Amount_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.Amount;
                }
                private static void _Amount_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Amount = v;
                }
                private static void _Amount_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.Amount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateDue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateDue",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateDue_OnValueChanged);
                private static void _DateDue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._DateDue, sf);
                }
                private static bool _DateDue_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.DateDue_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateDue_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateDue_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateDue_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.DateDue;
                }
                private static void _DateDue_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateDue = global::LightSwitchApplication.Invoice.DetailsClass.TruncateDate(v);
                }
                private static void _DateDue_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.DateDue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateInvoiced = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateInvoiced",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._DateInvoiced_OnValueChanged);
                private static void _DateInvoiced_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._DateInvoiced, sf);
                }
                private static bool _DateInvoiced_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.DateInvoiced_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateInvoiced_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateInvoiced_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateInvoiced_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.DateInvoiced;
                }
                private static void _DateInvoiced_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateInvoiced = global::LightSwitchApplication.Invoice.DetailsClass.TruncateDate(v);
                }
                private static void _DateInvoiced_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.DateInvoiced_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry
                    Notes = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry(
                        "Notes",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Notes_OnValueChanged);
                private static void _Notes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._Notes, sf);
                }
                private static bool _Notes_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.Notes_IsReadOnly(ref result);
                    return result;
                }
                private static void _Notes_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Notes_Validate(r);
                }
                private static string _Notes_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.Notes;
                }
                private static void _Notes_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Notes = v;
                }
                private static void _Notes_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.Notes_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry
                    SearchTerms = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Entry(
                        "SearchTerms",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._SearchTerms_OnValueChanged);
                private static void _SearchTerms_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._SearchTerms, sf);
                }
                private static bool _SearchTerms_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.SearchTerms_IsReadOnly(ref result);
                    return result;
                }
                private static void _SearchTerms_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SearchTerms_Validate(r);
                }
                private static string _SearchTerms_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.SearchTerms;
                }
                private static void _SearchTerms_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SearchTerms = v;
                }
                private static void _SearchTerms_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.SearchTerms_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus>.Entry
                    InvoiceStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus>.Entry(
                        "InvoiceStatus",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_GetCoreImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_Refresh,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._InvoiceStatus_OnValueChanged);
                private static void _InvoiceStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceStatus, sf);
                }
                private static bool _InvoiceStatus_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.InvoiceStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _InvoiceStatus_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.InvoiceStatus_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _InvoiceStatus_GetCoreImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.InvoiceStatus;
                }
                private static global::LightSwitchApplication.InvoiceStatus _InvoiceStatus_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.InvoiceStatus, global::LightSwitchApplication.InvoiceStatus.DetailsClass>(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus, ref d._InvoiceStatus);
                }
                private static void _InvoiceStatus_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, global::LightSwitchApplication.InvoiceStatus v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus, ref d._InvoiceStatus, (i, ev) => i.InvoiceStatus = ev, v);
                }
                private static void _InvoiceStatus_Refresh(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.InvoiceStatus, ref d._InvoiceStatus);
                }
                private static void _InvoiceStatus_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.InvoiceStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job>.Entry
                    Job = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job>.Entry(
                        "Job",
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_Stub,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_ComputeIsReadOnly,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_Validate,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_GetCoreImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_GetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_SetImplementationValue,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_Refresh,
                        global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties._Job_OnValueChanged);
                private static void _Job_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Invoice.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job>.Data> c, global::LightSwitchApplication.Invoice.DetailsClass d, object sf)
                {
                    c(d, ref d._Job, sf);
                }
                private static bool _Job_ComputeIsReadOnly(global::LightSwitchApplication.Invoice e)
                {
                    bool result = false;
                    e.Job_IsReadOnly(ref result);
                    return result;
                }
                private static void _Job_Validate(global::LightSwitchApplication.Invoice e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Job_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Job_GetCoreImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.ImplementationEntity.Job;
                }
                private static global::LightSwitchApplication.Job _Job_GetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Job, global::LightSwitchApplication.Job.DetailsClass>(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass d, global::LightSwitchApplication.Job v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job, ref d._Job, (i, ev) => i.Job = ev, v);
                }
                private static void _Job_Refresh(global::LightSwitchApplication.Invoice.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Invoice.DetailsClass.PropertySetProperties.Job, ref d._Job);
                }
                private static void _Job_OnValueChanged(global::LightSwitchApplication.Invoice e)
                {
                    e.Job_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data _Number;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, decimal>.Data _Amount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateDue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateInvoiced;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data _Notes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, string>.Data _SearchTerms;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.InvoiceStatus>.Data _InvoiceStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Invoice, global::LightSwitchApplication.Invoice.DetailsClass, global::LightSwitchApplication.Job>.Data _Job;
            
        }
    
        #endregion
    }
    
    #endregion
}
