

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class PurchaseOrderStatus : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PurchaseOrderStatus entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PurchaseOrderStatus()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PurchaseOrderStatus(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PurchaseOrderStatus> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderStatus_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseOrderStatus_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Status
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Status);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Status, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsLocked
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsLocked);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsLocked, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsLocked_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsLocked_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsLocked_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Seq
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Seq);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Seq, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Seq_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Seq_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Seq_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsClosed
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsClosed);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsClosed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsClosed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsClosed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsClosed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsOrdered
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsOrdered);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsOrdered, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsOrdered_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsOrdered_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsOrdered_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FgColor
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.FgColor);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.FgColor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FgColor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FgColor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FgColor_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BgColor
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.BgColor);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.BgColor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BgColor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BgColor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BgColor_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsRevised
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsRevised);
            }
            set
            {
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.SetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsRevised, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsRevised_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsRevised_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsRevised_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PurchaseOrder> PurchaseOrders
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.PurchaseOrders);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PurchaseOrder> PurchaseOrdersQuery
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetQuery(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.PurchaseOrders);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.JobMasterBOMItem> JobMasterBOMItems
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetValue(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.JobMasterBOMItems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.JobMasterBOMItem> JobMasterBOMItemsQuery
        {
            get
            {
                return global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.GetQuery(this, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.JobMasterBOMItems);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PurchaseOrderStatus,
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass,
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.IImplementation,
                global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>.Entry
                __PurchaseOrderStatusEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>.Entry(
                    global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.__PurchaseOrderStatus_CreateNew,
                    global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.__PurchaseOrderStatus_Created,
                    global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.__PurchaseOrderStatus_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PurchaseOrderStatus __PurchaseOrderStatus_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PurchaseOrderStatus> es)
            {
                return new global::LightSwitchApplication.PurchaseOrderStatus(es);
            }
            private static void __PurchaseOrderStatus_Created(global::LightSwitchApplication.PurchaseOrderStatus e)
            {
                e.PurchaseOrderStatus_Created();
            }
            private static bool __PurchaseOrderStatus_AllowSaveWithErrors(global::LightSwitchApplication.PurchaseOrderStatus e)
            {
                bool result = false;
                e.PurchaseOrderStatus_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool> IsLocked
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsLocked) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int> Seq
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.Seq) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool> IsClosed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsClosed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool> IsOrdered
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsOrdered) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string> FgColor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.FgColor) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string> BgColor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.BgColor) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool> IsRevised
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.IsRevised) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder> PurchaseOrders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.PurchaseOrders) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem> JobMasterBOMItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.JobMasterBOMItems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Status { get; set; }
                new bool IsLocked { get; set; }
                new int Seq { get; set; }
                new bool IsClosed { get; set; }
                new bool IsOrdered { get; set; }
                new string FgColor { get; set; }
                new string BgColor { get; set; }
                new byte[] RowVersion { get; set; }
                new bool IsRevised { get; set; }
                new global::System.Collections.IEnumerable PurchaseOrders { get; }
                new global::System.Collections.IEnumerable JobMasterBOMItems { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry(
                        "Status",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Status_OnValueChanged);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static bool _Status_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.Status_IsReadOnly(ref result);
                    return result;
                }
                private static void _Status_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static string _Status_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.Status;
                }
                private static void _Status_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Status = v;
                }
                private static void _Status_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.Status_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry
                    IsLocked = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry(
                        "IsLocked",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsLocked_OnValueChanged);
                private static void _IsLocked_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._IsLocked, sf);
                }
                private static bool _IsLocked_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.IsLocked_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsLocked_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsLocked_Validate(r);
                }
                private static bool _IsLocked_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.IsLocked;
                }
                private static void _IsLocked_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsLocked = v;
                }
                private static void _IsLocked_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.IsLocked_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Entry
                    Seq = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Entry(
                        "Seq",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._Seq_OnValueChanged);
                private static void _Seq_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._Seq, sf);
                }
                private static bool _Seq_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.Seq_IsReadOnly(ref result);
                    return result;
                }
                private static void _Seq_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Seq_Validate(r);
                }
                private static int _Seq_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.Seq;
                }
                private static void _Seq_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Seq = v;
                }
                private static void _Seq_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.Seq_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry
                    IsClosed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry(
                        "IsClosed",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsClosed_OnValueChanged);
                private static void _IsClosed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._IsClosed, sf);
                }
                private static bool _IsClosed_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.IsClosed_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsClosed_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsClosed_Validate(r);
                }
                private static bool _IsClosed_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.IsClosed;
                }
                private static void _IsClosed_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsClosed = v;
                }
                private static void _IsClosed_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.IsClosed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry
                    IsOrdered = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry(
                        "IsOrdered",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsOrdered_OnValueChanged);
                private static void _IsOrdered_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._IsOrdered, sf);
                }
                private static bool _IsOrdered_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.IsOrdered_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsOrdered_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsOrdered_Validate(r);
                }
                private static bool _IsOrdered_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.IsOrdered;
                }
                private static void _IsOrdered_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsOrdered = v;
                }
                private static void _IsOrdered_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.IsOrdered_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry
                    FgColor = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry(
                        "FgColor",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._FgColor_OnValueChanged);
                private static void _FgColor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._FgColor, sf);
                }
                private static bool _FgColor_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.FgColor_IsReadOnly(ref result);
                    return result;
                }
                private static void _FgColor_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FgColor_Validate(r);
                }
                private static string _FgColor_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.FgColor;
                }
                private static void _FgColor_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FgColor = v;
                }
                private static void _FgColor_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.FgColor_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry
                    BgColor = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Entry(
                        "BgColor",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._BgColor_OnValueChanged);
                private static void _BgColor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._BgColor, sf);
                }
                private static bool _BgColor_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.BgColor_IsReadOnly(ref result);
                    return result;
                }
                private static void _BgColor_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.BgColor_Validate(r);
                }
                private static string _BgColor_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.BgColor;
                }
                private static void _BgColor_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, string v)
                {
                    d.ImplementationEntity.BgColor = v;
                }
                private static void _BgColor_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.BgColor_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry
                    IsRevised = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Entry(
                        "IsRevised",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_ComputeIsReadOnly,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_Validate,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_GetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_SetImplementationValue,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._IsRevised_OnValueChanged);
                private static void _IsRevised_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._IsRevised, sf);
                }
                private static bool _IsRevised_ComputeIsReadOnly(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    bool result = false;
                    e.IsRevised_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsRevised_Validate(global::LightSwitchApplication.PurchaseOrderStatus e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsRevised_Validate(r);
                }
                private static bool _IsRevised_GetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.IsRevised;
                }
                private static void _IsRevised_SetImplementationValue(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsRevised = v;
                }
                private static void _IsRevised_OnValueChanged(global::LightSwitchApplication.PurchaseOrderStatus e)
                {
                    e.IsRevised_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Entry
                    PurchaseOrders = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Entry(
                        "PurchaseOrders",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._PurchaseOrders_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._PurchaseOrders_GetReferencedEntities,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._PurchaseOrders_GetEntityCollection);
                private static void _PurchaseOrders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchaseOrders, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PurchaseOrder> _PurchaseOrders_GetReferencedEntities(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PurchaseOrder, global::LightSwitchApplication.PurchaseOrder.DetailsClass>(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.PurchaseOrders, ref d._PurchaseOrders);
                }
                private static global::System.Collections.IEnumerable _PurchaseOrders_GetEntityCollection(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchaseOrders;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem>.Entry
                    JobMasterBOMItems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem>.Entry(
                        "JobMasterBOMItems",
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._JobMasterBOMItems_Stub,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._JobMasterBOMItems_GetReferencedEntities,
                        global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties._JobMasterBOMItems_GetEntityCollection);
                private static void _JobMasterBOMItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem>.Data> c, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d, object sf)
                {
                    c(d, ref d._JobMasterBOMItems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.JobMasterBOMItem> _JobMasterBOMItems_GetReferencedEntities(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.JobMasterBOMItem, global::LightSwitchApplication.JobMasterBOMItem.DetailsClass>(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass.PropertySetProperties.JobMasterBOMItems, ref d._JobMasterBOMItems);
                }
                private static global::System.Collections.IEnumerable _JobMasterBOMItems_GetEntityCollection(global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass d)
                {
                    return d.ImplementationEntity.JobMasterBOMItems;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data _IsLocked;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, int>.Data _Seq;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data _IsClosed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data _IsOrdered;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data _FgColor;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, string>.Data _BgColor;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, bool>.Data _IsRevised;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.PurchaseOrder>.Data _PurchaseOrders;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PurchaseOrderStatus, global::LightSwitchApplication.PurchaseOrderStatus.DetailsClass, global::LightSwitchApplication.JobMasterBOMItem>.Data _JobMasterBOMItems;
            
        }
    
        #endregion
    }
    
    #endregion
}
